todo/core/urls.py
from django.urls import path

from .views import LoginView, LogoutView, SignupView

urlpatterns = [
    path("accounts/login/", LoginView.as_view(), name="account_login"),
    path("accounts/signup/", SignupView.as_view(), name="account_signup"),
    path("accounts/logout/", LogoutView.as_view(), name="account_logout"),
]

todo/project/urls.py
from django.contrib import admin
from django.urls import include, path

# Base urls
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.tasks.urls")),
    path("", include("todo.core.urls")),
]

todo/tasks/urls.py
from django.urls import path

from .views.projects import ProjectCreateView, ProjectDeleteView, ProjectListView, ProjectUpdateView
from .views.tasks import PriorityUpdateView, TaskCompleteView, TaskCreateView, TaskDeleteView, TaskUpdateView

app_name = "tasks"

# Base urls
urlpatterns = [
    path("", ProjectListView.as_view(), name="project_list"),
]

# Projects HTMX urls
urlpatterns += [
    path("projects/<int:pk>/task-create/", TaskCreateView.as_view(), name="task_create"),
    path("projects/<int:pk>/update/", ProjectUpdateView.as_view(), name="project_update"),
    path("projects/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project_delete"),
    path("projects/create/", ProjectCreateView.as_view(), name="project_create"),
]

# Tasks HTMX urls
urlpatterns += [
    path("tasks/<int:pk>/priority/<int:priority>/", PriorityUpdateView.as_view(), name="task_priority"),
    path("tasks/<int:pk>/complete/", TaskCompleteView.as_view(), name="task_complete"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task_update"),
]

todo/tasks/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Project(models.Model):
    """
    Stores the details of a project that belongs to a user. The
    project can have multiple tasks associated with it.
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="projects")
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    """
    Stores the details of a task that belongs to a project. The
    task can be marked as complete or incomplete. The task can
    have a description, deadline, and priority.
    """

    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="tasks")
    complete = models.BooleanField(default=False)
    description = models.TextField()
    deadline = models.DateTimeField(null=True, blank=True)
    priority = models.PositiveIntegerField(null=True, blank=True)

    def set_priority(self, new_priority: int) -> None:
        """Set the priority of the task.

        Args:
            new_priority (int): The new priority of the task.
        """

        # Get the current priority of the task
        current_priority = self.priority

        # If the new priority is the same as the current priority, return
        if new_priority == current_priority:
            return

        # Get the tasks in the project
        tasks = Task.objects.filter(project=self.project)

        # If the new priority is greater than the current priority
        if new_priority > current_priority:
            # Update the priority of the tasks between the current priority and the new priority
            tasks.filter(
                priority__gt=current_priority,
                priority__lte=new_priority,
            ).update(priority=models.F("priority") - 1)
        # If the new priority is less than the current priority
        else:
            # Update the priority of the tasks between the new priority and the current priority
            tasks.filter(
                priority__gte=new_priority,
                priority__lt=current_priority,
            ).update(priority=models.F("priority") + 1)

        # Update the priority of the task
        self.priority = new_priority
        self.save()

    def save(self, *args, **kwargs) -> None:
        """
        Override the save method to set the priority of the task
        if it is not provided. The priority is set to the total
        number of tasks in the project + 1.
        """

        if self.priority is None:
            self.priority = Task.objects.filter(project=self.project).count() + 1
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.description[:18]

    class Meta:
        ordering = [
            # Since we are using null=True and blank=True for the priority field,
            # but setting the priority in the save method, we don't need to ensure
            # that the null values are sorted last. We can just sort by the priority
            # field in ascending order.
            "priority",
            # As a fallback, we can sort by the id of the task to ensure a consistent order.
            "id",
        ]

todo/tasks/forms.py
from crispy_forms.helper import FormHelper
from django import forms

from todo.tasks.models import Project, Task


class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)

        # Disable the form tag to use the form with htmx
        self.helper.form_tag = False


class TaskForm(BaseForm):
    class Meta:
        model = Task
        fields = ["description", "deadline"]
        widgets = {
            "description": forms.TextInput(attrs={"placeholder": "Enter a task description"}),
            "deadline": forms.DateTimeInput(attrs={"type": "datetime-local"}),
        }


class ProjectForm(BaseForm):
    class Meta:
        model = Project
        fields = ["name"]
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "Enter a project name"}),
        }

todo/project/views.py
from allauth.account.views import LogoutView

from todo.project.utils.modal import ModalMixin


class CustomLogoutView(ModalMixin, LogoutView):
    """Custom logout view that redirects to the login page using htmx."""

    def post(self, *args, **kwargs):
        response = super().post(*args, **kwargs)
        response.status_code = 200
        response.headers["HX-Redirect"] = "/accounts/login/"
        return response

todo/tasks/views/projects.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from todo.core.mixins import ModalMixin
from todo.core.utils.htmx import render_swap, reswap
from todo.core.utils.modal import hide_modal
from todo.tasks.forms import ProjectForm
from todo.tasks.models import Project


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "tasks/project/list.html"
    context_object_name = "projects"

    def get_queryset(self) -> QuerySet[Project]:
        return self.request.user.projects.all()


class ProjectCreateView(LoginRequiredMixin, ModalMixin, CreateView):
    model = Project
    form_class = ProjectForm
    template_name = "tasks/project/create_modal.html"
    success_url = "/"

    @hide_modal
    def form_valid(self, form: ProjectForm) -> HttpResponse:
        # Set the user of the project to the current user
        form.instance.user = self.request.user

        # Run the parent form_valid method to save the form
        super().form_valid(form)

        # Return the rendered project item template
        # to be added into the project list.
        return render_swap(
            self.request,
            "tasks/project/item.html",
            context={"project": form.instance},
            params={
                "swap": "beforeend",
                "target": "[data-project-list]",
                "select": ".card",
            },
        )


class ProjectUpdateView(LoginRequiredMixin, ModalMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = "tasks/project/update_modal.html"
    success_url = "/"

    @hide_modal
    def form_valid(self, form: ProjectForm) -> HttpResponse:
        # Run the parent form_valid method to save the form
        super().form_valid(form)

        # Return the rendered project item template
        # to be swapped inside the project list.
        return render_swap(
            self.request,
            "tasks/project/item.html",
            context={"project": form.instance},
            params={
                "swap": "innerHTML",
                "target": f'[data-project="{form.instance.pk}"] .project-name',
                "select": ".project-name",
            },
        )


class ProjectDeleteView(LoginRequiredMixin, ModalMixin, DeleteView):
    model = Project
    template_name = "tasks/project/delete_modal.html"
    success_url = "/"

    def get_queryset(self) -> QuerySet[Project]:
        # Filter the queryset to only return tasks
        # that are owned by the user.
        return self.request.user.projects.all()

    @hide_modal
    def delete(self, *args, **kwargs) -> HttpResponse:
        # Run the parent delete method to delete the task
        response = super().delete(*args, **kwargs)

        # Status code 200 is required by HTMX
        # to delete the item from the DOM.
        # See: https://htmx.org/attributes/hx-delete/ for more information.
        response.status_code = 200

        # Return the response object with the project item
        # as a target to remove.
        return reswap(
            response,
            {"target": f'[data-project="{self.kwargs["pk"]}"]'},
        )

todo/tasks/views/tasks.py
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import CreateView, DeleteView, UpdateView, View

from todo.core.mixins import ModalMixin
from todo.core.utils.htmx import render_swap, reswap
from todo.core.utils.modal import hide_modal
from todo.tasks.forms import TaskForm
from todo.tasks.models import Project, Task


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/task/create_form.html"
    success_url = "/"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        # Add the project primary key to the context
        context["project"] = {"pk": self.kwargs["pk"]}
        return context

    def form_valid(self, form: TaskForm) -> HttpResponse:
        # Ensure the project is owned by the user
        project: Project = get_object_or_404(Project, pk=self.kwargs["pk"], user=self.request.user)
        form.instance.project = project

        # Run the parent form_valid method to save the form
        # and ensure that the task form is still valid.
        super().form_valid(form)

        # Return the rendered task item template
        # to be swapped into the project task list.
        return render_swap(
            self.request,
            "tasks/task/item.html",
            context={"task": form.instance},
            params={
                "swap": "beforeend",
                "target": f'[data-task-list="{self.kwargs['pk']}"]',
            },
        )


class TaskUpdateView(LoginRequiredMixin, ModalMixin, UpdateView):
    template_name = "tasks/task/update_modal.html"
    model = Task
    form_class = TaskForm
    success_url = "/"

    def get_queryset(self) -> QuerySet[Task]:
        # Filter the queryset to only return tasks
        # that are owned by the user.
        return super().get_queryset().filter(project__user=self.request.user)

    @hide_modal
    def form_valid(self, form: TaskForm) -> HttpResponse:
        # Run the parent form_valid method to save the form
        super().form_valid(form)

        # Return the rendered task item template
        # to be swapped into the project task list.
        return render_swap(
            self.request,
            "tasks/task/item.html",
            context={"task": form.instance},
            params={
                "target": f'[data-task="{form.instance.pk}"]',
                "select": "li",
            },
        )


class TaskDeleteView(LoginRequiredMixin, ModalMixin, DeleteView):
    model = Task
    template_name = "tasks/task/delete_modal.html"
    success_url = "/"

    def get_queryset(self) -> QuerySet[Task]:
        # Filter the queryset to only return tasks
        # that are owned by the user.
        return super().get_queryset().filter(project__user=self.request.user)

    @hide_modal
    def delete(self, *args, **kwargs) -> HttpResponse:
        # Run the parent delete method to delete the task
        response = super().delete(*args, **kwargs)

        # Status code 200 is required by HTMX
        # to delete the task from the DOM
        # See: https://htmx.org/attributes/hx-delete/ for more information.
        response.status_code = 200

        # Return the response with the task item to be removed
        # as a HTMX target to be swapped.
        return reswap(
            response,
            {"target": f'[data-task="{self.kwargs["pk"]}"]'},
        )


class PriorityUpdateView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest, pk: int, priority: int) -> HttpResponse:
        task: Task = get_object_or_404(Task, pk=pk, project__user=request.user)

        # Ensure the priority is greater than 0
        # and is different from the current task priority.
        if priority > 0 and priority != task.priority:
            # Update the task priority
            task.set_priority(priority)

        return HttpResponse(status=204)


class TaskCompleteView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest, pk: int) -> HttpResponse:
        # Get the task object and toggle the complete status
        task = get_object_or_404(Task, pk=pk, project__user=request.user)
        task.complete = not task.complete
        task.save()

        # Return the task item template to be swapped into the project task list
        return render(
            request,
            "tasks/task/item.html",
            {"task": task},
        )

todo/tasks/templates/tasks/project/create_modal.html
{% extends "modal/base.html" %}

{% load crispy_forms_tags %}

{% block title %}Create project{% endblock %}

{% block body %}
    <form
        id="create-project-form"
        method="post"
        hx-post="{% url "tasks:project_create" %}"
        hx-swap="outerHTML"
        hx-disabled-elt='#create-project-form .form-control, [form="create-project-form"]'
        hx-select="#create-project-form">
        {% crispy form %}
    </form>
{% endblock %}

{% block footer %}
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    <input type="submit" class="btn btn-success" value="Create" form="create-project-form"/>
{% endblock %}

todo/tasks/templates/tasks/project/delete_modal.html
{% extends "modal/base.html" %}

{% block title %}Delete project{% endblock %}

{% block body %}
    <p>Are you sure you want to delete the "{{ project.name }}" project?</p>
{% endblock %}

{% block footer %}
    <form
        hx-delete="{% url "tasks:project_delete" pk=project.pk %}"
        hx-disabled-elt="form[hx-delete] button"
        hx-swap="outerHTML">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
{% endblock %}

todo/tasks/templates/tasks/project/item.html
{% load modal %}
{% load icons %}

<div class="card rounded-4 rounded-top-0 shadow" x-data data-project="{{ project.pk }}">
    <div class="card-header d-flex align-items-center gap-2 rounded-top-0 bg-primary text-white py-3">
        {% ic "calendar-week" %}
        <div class="flex-grow-1 fw-bold project-name">
            {{ project.name }}
        </div>
        <div class="d-flex align-items-center gap-2 opacity-0 parent-hover">
            <a href="#" {% modalurl "tasks:project_update" pk=project.pk %}>
                {% ic "pencil" "text-white opacity-50" %}
            </a>
            <div class="vr"></div>
            <a href="#" {% modalurl "tasks:project_delete" pk=project.pk %}>
                {% ic "trash" "text-white opacity-50" %}
            </a>
        </div>
    </div>
    <div class="card-header border-bottom d-flex gap-3 align-items-center py-2">
        {% ic "plus-circle" "text-success fs-4" %}
        {% include "tasks/task/create_form.html" with project=project %}
    </div>
    <div class="card-body p-0">
        <ul class="list-group list-group-flush rounded-4 rounded-top-0 task-list"
            x-sort.ghost="handleTaskPriority"
            data-task-list="{{ project.pk }}">
            {% for task in project.tasks.all %}
                {% include "tasks/task/item.html" with task=task %}
            {% endfor %}
        </ul>
    </div>
</div>

todo/tasks/templates/tasks/project/list.html
{% extends "layouts/default.html" %}

{% load modal %}
{% load icons %}

{% block content %}
    <div class="vstack gap-5 mb-5" data-project-list>
        {% for project in projects %}
            {% include "tasks/project/item.html" with project=project %}
        {% endfor %}
    </div>

    <div class="text-center">
        <a href="#" {% modalurl "tasks:project_create" %} class="btn btn-primary btn-lg shadow">
            {% ic "plus" %} Create Project
        </a>
    </div>
{% endblock content %}

todo/tasks/templates/tasks/project/update_modal.html
{% extends "modal/base.html" %}

{% load crispy_forms_tags %}

{% block title %}Edit project{% endblock %}

{% block body %}
    <form
        id="update-project-form"
        method="post"
        hx-post="{% url "tasks:project_update" pk=form.instance.pk %}"
        hx-disabled-elt='#update-project-form .form-control, [form="update-project-form"]'
        hx-swap="outerHTML"
        hx-select="#update-project-form">
        {% crispy form %}
    </form>
{% endblock %}

{% block footer %}
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    <input type="submit" class="btn btn-success" value="Save changes" form="update-project-form"/>
{% endblock %}